e:
  conf: 
    authServer: http://localhost:9999/uaa
    
spring:
   application:
            name: gateway
server:
  port: 8080
zuul: 
  routes: 
      upm:
        sensitive-headers: true
        stripPrefix: true
        path: /upm/**
        url: http://localhost:18080/
        
      upm-ui: 
        sensitive-headers: true
        stripPrefix: true
        path: /upm-ui/**
        url: http://localhost:8888/
        
      log:
        sensitive-headers: true
        stripPrefix: true
        path: /log/**
        url: http://localhost:28080/
        
      log-ui:
        sensitive-headers: true
        stripPrefix: true
        path: /log-ui/**
        url: http://localhost:8888/
        
        
      demo:
        sensitive-headers: true
        stripPrefix: true
        path: /demo/**
        #url: http://localhost:38080/
        serviceId: demo
        
      demo-ui:
        sensitive-headers: true
        stripPrefix: true
        path: /demo-ui/**
        url: http://localhost:8888/
        
        
      auth: 
        sensitive-headers: true
        stripPrefix: true
        path: /uaa/**
        url: http://localhost:9999/
      
      ms-ui-home: 
        sensitive-headers: true
        stripPrefix: true
        path: /
        url: http://localhost:8888/home.html
        
      ms-ui: 
        sensitive-headers: true
        stripPrefix: true
        path: /**
        url: http://localhost:8888/
      
        
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # 指定注册中心的地址
  instance:
    preferIpAddress: true
    


security:
  user:
    password: none
  oauth2:
    client:
      accessTokenUri: ${e.conf.authServer}/oauth/token
      userAuthorizationUri: ${e.conf.authServer}/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
          -----END PUBLIC KEY-----